-- first drop everything
drop table passwd;
drop table sessions;
drop table users;

-- ddl
create table users (
  userid       number        generated by default as identity,
  username     varchar2(50)  unique not null,
  pwdhash      varchar2(256) not null,
  fname        varchar2(50)  not null,
  lname        varchar2(50)  not null,
  created_ts   timestamp(2)  with time zone default current_timestamp,
  updated_ts   timestamp(2)  with time zone default current_timestamp,
  primary key (userid)
);

create table sessions (
  snid         number        generated by default as identity,
  userid       number        not null,
  toknm        varchar2(16)  not null,
  expiry_sec   number        default 300,
  created_ts   timestamp(2)  with time zone default current_timestamp,
  primary key (snid),
  foreign key (userid) references users
);

-- procedures
create or replace procedure register_user (unm in varchar2, fnm in varchar2, lnm in varchar2, pwd in varchar2, res out varchar2)
is
begin
  select 'OK' into res from dual;
end;
/

create or replace procedure login_user (unm in varchar2, pwd in varchar2, tok out varchar2)
is
begin
  select standard_hash(unm || 'PinkSalt' || pwd, 'SHA1') into tok from dual;
end;
/

